### ISSUE TITLE
Addon seems to have become corrupted

### ISSUE THREAD

**Issue by VaasKahnGrim** [EstevanTH/GMod_Momo_Encryption_Library#1]
Currently I get the following in my console:

Not loading addon 'Momo's Encryption Library' - Invalid filename: 'lua/autorun/momo_encryption.lua': Code point 6
Couldn't mount addon file 'addons/momos_encryption_library_939273135.gma' from 'Momo's Encryption Library' (939273135)
Removing bad addon addons/momos_encryption_library_939273135.gma

**Comment by EstevanTH** [comment]
Thanks! To solve this I only use valid filename characters by now!
